SystemUIGoogle: Do not run R8 as full mode
* Build breakage occurred
* Also enable ignore warnings option

Log:
Error: Missing class androidx.appcompat.graphics.drawable.DrawableWrapper (referenced from: void com.google.android.material.shadow.ShadowDrawableWrapper.<init>(android.content.Context, android.graphics.drawable.Drawable, float, float, float) and 3 other contexts)
Missing class java.lang.reflect.AnnotatedType (referenced from: java.lang.reflect.AnnotatedType[] com.google.common.reflect.Invokable$ConstructorInvokable.getAnnotatedParameterTypes() and 6 other contexts)
Exception in thread "main" com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at Version.fakeStackEntry(Version_8.3.21-dev.java:0)
	at com.android.tools.r8.Q.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:5)
	at com.android.tools.r8.internal.po.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:244)
	at com.android.tools.r8.internal.po.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:90)
	at com.android.tools.r8.internal.po.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:909)
	at com.android.tools.r8.R8.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:8254)
	at com.android.tools.r8.R8.run(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:3)
	at com.android.tools.r8wrappers.R8Wrapper.main(R8Wrapper.java:114)
Caused by: com.android.tools.r8.internal.h: Missing class androidx.appcompat.graphics.drawable.DrawableWrapper (referenced from: void com.google.android.material.shadow.ShadowDrawableWrapper.<init>(android.content.Context, android.graphics.drawable.Drawable, float, float, float) and 3 other contexts)
Missing class java.lang.reflect.AnnotatedType (referenced from: java.lang.reflect.AnnotatedType[] com.google.common.reflect.Invokable$ConstructorInvokable.getAnnotatedParameterTypes() and 6 other contexts)
	at com.android.tools.r8.internal.X30.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:346)
	at com.android.tools.r8.internal.X30.error(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:112)
	at com.android.tools.r8.shaking.M.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:4332)
	at com.android.tools.r8.shaking.M.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:47987)
	at com.android.tools.r8.R8.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:7997)
	at com.android.tools.r8.R8.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:9485)
	at com.android.tools.r8.R8.b(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:1133)
	at com.android.tools.r8.internal.po.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:906)
	... 3 more
	Suppressed: java.lang.RuntimeException: com.android.tools.r8.internal.h: Missing class androidx.appcompat.graphics.drawable.DrawableWrapper (referenced from: void com.google.android.material.shadow.ShadowDrawableWrapper.<init>(android.content.Context, android.graphics.drawable.Drawable, float, float, float) and 3 other contexts)
Missing class java.lang.reflect.AnnotatedType (referenced from: java.lang.reflect.AnnotatedType[] com.google.common.reflect.Invokable$ConstructorInvokable.getAnnotatedParameterTypes() and 6 other contexts)
		at com.android.tools.r8.internal.X30.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:255)
		at com.android.tools.r8.shaking.M.a(R8_8.3.21-dev_4b703027643c0c51f37766059beb74fb1aa0a04f0069be5f7b0a5fd77d2c3064:4334)
		... 8 more
	Caused by: [CIRCULAR REFERENCE: com.android.tools.r8.internal.h: Missing class androidx.appcompat.graphics.drawable.DrawableWrapper (referenced from: void com.google.android.material.shadow.ShadowDrawableWrapper.<init>(android.content.Context, android.graphics.drawable.Drawable, float, float, float) and 3 other contexts)
Missing class java.lang.reflect.AnnotatedType (referenced from: java.lang.reflect.AnnotatedType[] com.google.common.reflect.Invokable$ConstructorInvokable.getAnnotatedParameterTypes() and 6 other contexts)]

Change-Id: Ie2310ca690ea40f9c526f822f7efacc8700e0ba5